//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaBrowser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaBrowser.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _0 {
            get {
                object obj = ResourceManager.GetObject("_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _10 {
            get {
                object obj = ResourceManager.GetObject("_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _12 {
            get {
                object obj = ResourceManager.GetObject("_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _13 {
            get {
                object obj = ResourceManager.GetObject("_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _14 {
            get {
                object obj = ResourceManager.GetObject("_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _15 {
            get {
                object obj = ResourceManager.GetObject("_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _16 {
            get {
                object obj = ResourceManager.GetObject("_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _17 {
            get {
                object obj = ResourceManager.GetObject("_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _18 {
            get {
                object obj = ResourceManager.GetObject("_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _19 {
            get {
                object obj = ResourceManager.GetObject("_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20 {
            get {
                object obj = ResourceManager.GetObject("_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _21 {
            get {
                object obj = ResourceManager.GetObject("_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _22 {
            get {
                object obj = ResourceManager.GetObject("_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _23 {
            get {
                object obj = ResourceManager.GetObject("_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _24 {
            get {
                object obj = ResourceManager.GetObject("_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _25 {
            get {
                object obj = ResourceManager.GetObject("_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _26 {
            get {
                object obj = ResourceManager.GetObject("_26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _27 {
            get {
                object obj = ResourceManager.GetObject("_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _28 {
            get {
                object obj = ResourceManager.GetObject("_28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _29 {
            get {
                object obj = ResourceManager.GetObject("_29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _30 {
            get {
                object obj = ResourceManager.GetObject("_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _31 {
            get {
                object obj = ResourceManager.GetObject("_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _32 {
            get {
                object obj = ResourceManager.GetObject("_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _33 {
            get {
                object obj = ResourceManager.GetObject("_33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _34 {
            get {
                object obj = ResourceManager.GetObject("_34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _35 {
            get {
                object obj = ResourceManager.GetObject("_35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _36 {
            get {
                object obj = ResourceManager.GetObject("_36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _37 {
            get {
                object obj = ResourceManager.GetObject("_37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _38 {
            get {
                object obj = ResourceManager.GetObject("_38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _39 {
            get {
                object obj = ResourceManager.GetObject("_39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _40 {
            get {
                object obj = ResourceManager.GetObject("_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _41 {
            get {
                object obj = ResourceManager.GetObject("_41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _42 {
            get {
                object obj = ResourceManager.GetObject("_42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _43 {
            get {
                object obj = ResourceManager.GetObject("_43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _44 {
            get {
                object obj = ResourceManager.GetObject("_44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _45 {
            get {
                object obj = ResourceManager.GetObject("_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _46 {
            get {
                object obj = ResourceManager.GetObject("_46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _47 {
            get {
                object obj = ResourceManager.GetObject("_47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _5 {
            get {
                object obj = ResourceManager.GetObject("_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6 {
            get {
                object obj = ResourceManager.GetObject("_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _7 {
            get {
                object obj = ResourceManager.GetObject("_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _8 {
            get {
                object obj = ResourceManager.GetObject("_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _9 {
            get {
                object obj = ResourceManager.GetObject("_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Animations {
            get {
                object obj = ResourceManager.GetObject("Animations", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aspect_169 {
            get {
                object obj = ResourceManager.GetObject("aspect_169", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aspect_1851 {
            get {
                object obj = ResourceManager.GetObject("aspect_1851", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aspect_2391 {
            get {
                object obj = ResourceManager.GetObject("aspect_2391", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aspect_32 {
            get {
                object obj = ResourceManager.GetObject("aspect_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aspect_43 {
            get {
                object obj = ResourceManager.GetObject("aspect_43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] AutoScroller {
            get {
                object obj = ResourceManager.GetObject("AutoScroller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Backdrop {
            get {
                object obj = ResourceManager.GetObject("Backdrop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackgroundBlack {
            get {
                object obj = ResourceManager.GetObject("BackgroundBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackgroundDefault {
            get {
                object obj = ResourceManager.GetObject("BackgroundDefault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap banner {
            get {
                object obj = ResourceManager.GetObject("banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackBtnAlpha50 {
            get {
                object obj = ResourceManager.GetObject("BlackBtnAlpha50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackBtnAlpha65 {
            get {
                object obj = ResourceManager.GetObject("BlackBtnAlpha65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlankGraphic {
            get {
                object obj = ResourceManager.GetObject("BlankGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonDisabled {
            get {
                object obj = ResourceManager.GetObject("ButtonDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonDormant {
            get {
                object obj = ResourceManager.GetObject("ButtonDormant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonLeftFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonLeftFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonLeftFocusBlack {
            get {
                object obj = ResourceManager.GetObject("ButtonLeftFocusBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonLeftFocusDefault {
            get {
                object obj = ResourceManager.GetObject("ButtonLeftFocusDefault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonLeftFocusOverlay {
            get {
                object obj = ResourceManager.GetObject("ButtonLeftFocusOverlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonNoFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonSelection {
            get {
                object obj = ResourceManager.GetObject("ButtonSelection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonSelection2 {
            get {
                object obj = ResourceManager.GetObject("ButtonSelection2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] CheckBox {
            get {
                object obj = ResourceManager.GetObject("CheckBox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CheckBoxCheckedFocus {
            get {
                object obj = ResourceManager.GetObject("CheckBoxCheckedFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CheckBoxCheckedNoFocus {
            get {
                object obj = ResourceManager.GetObject("CheckBoxCheckedNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CheckBoxUncheckedFocus {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUncheckedFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CheckBoxUncheckedNoFocus {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUncheckedNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_aac {
            get {
                object obj = ResourceManager.GetObject("codec_aac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_ac3 {
            get {
                object obj = ResourceManager.GetObject("codec_ac3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_divx {
            get {
                object obj = ResourceManager.GetObject("codec_divx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_dts {
            get {
                object obj = ResourceManager.GetObject("codec_dts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_h264 {
            get {
                object obj = ResourceManager.GetObject("codec_h264", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_mpegaudio {
            get {
                object obj = ResourceManager.GetObject("codec_mpegaudio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_vc1 {
            get {
                object obj = ResourceManager.GetObject("codec_vc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_wma {
            get {
                object obj = ResourceManager.GetObject("codec_wma", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_wmv {
            get {
                object obj = ResourceManager.GetObject("codec_wmv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_xvid {
            get {
                object obj = ResourceManager.GetObject("codec_xvid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ColorSpinner {
            get {
                object obj = ResourceManager.GetObject("ColorSpinner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Config {
            get {
                object obj = ResourceManager.GetObject("Config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ConfigPage {
            get {
                object obj = ResourceManager.GetObject("ConfigPage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DecrementFocused {
            get {
                object obj = ResourceManager.GetObject("DecrementFocused", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DecrementNoFocus {
            get {
                object obj = ResourceManager.GetObject("DecrementNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DetailBorderShadow {
            get {
                object obj = ResourceManager.GetObject("DetailBorderShadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Selected.
        /// </summary>
        internal static string DialogCaption {
            get {
                return ResourceManager.GetString("DialogCaption", resourceCulture);
            }
        }
        
        internal static byte[] DirectorButton {
            get {
                object obj = ResourceManager.GetObject("DirectorButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Directors {
            get {
                object obj = ResourceManager.GetObject("Directors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ExternalPlayback {
            get {
                object obj = ResourceManager.GetObject("ExternalPlayback", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flashHorB {
            get {
                object obj = ResourceManager.GetObject("flashHorB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flashHorT {
            get {
                object obj = ResourceManager.GetObject("flashHorT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] FocusSelector {
            get {
                object obj = ResourceManager.GetObject("FocusSelector", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] FontsDefault {
            get {
                object obj = ResourceManager.GetObject("FontsDefault", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FontsSmall {
            get {
                object obj = ResourceManager.GetObject("FontsSmall", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GenreButton {
            get {
                object obj = ResourceManager.GetObject("GenreButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GenreList {
            get {
                object obj = ResourceManager.GetObject("GenreList", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HD {
            get {
                object obj = ResourceManager.GetObject("HD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hd1080 {
            get {
                object obj = ResourceManager.GetObject("hd1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hd720 {
            get {
                object obj = ResourceManager.GetObject("hd720", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hdtype_1080 {
            get {
                object obj = ResourceManager.GetObject("hdtype_1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hdtype_720 {
            get {
                object obj = ResourceManager.GetObject("hdtype_720", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconActors {
            get {
                object obj = ResourceManager.GetObject("IconActors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconDelete {
            get {
                object obj = ResourceManager.GetObject("IconDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconMusic {
            get {
                object obj = ResourceManager.GetObject("IconMusic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconPlay {
            get {
                object obj = ResourceManager.GetObject("IconPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconRefresh {
            get {
                object obj = ResourceManager.GetObject("IconRefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconResume {
            get {
                object obj = ResourceManager.GetObject("IconResume", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconShuffle {
            get {
                object obj = ResourceManager.GetObject("IconShuffle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconSummary {
            get {
                object obj = ResourceManager.GetObject("IconSummary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconTrailer {
            get {
                object obj = ResourceManager.GetObject("IconTrailer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ImageButton {
            get {
                object obj = ResourceManager.GetObject("ImageButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Images {
            get {
                object obj = ResourceManager.GetObject("Images", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IncrementFocused {
            get {
                object obj = ResourceManager.GetObject("IncrementFocused", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IncrementNoFocus {
            get {
                object obj = ResourceManager.GetObject("IncrementNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Index {
            get {
                object obj = ResourceManager.GetObject("Index", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] InfoMarquee {
            get {
                object obj = ResourceManager.GetObject("InfoMarquee", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ItemButton {
            get {
                object obj = ResourceManager.GetObject("ItemButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ItemPoster {
            get {
                object obj = ResourceManager.GetObject("ItemPoster", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LastWatched {
            get {
                object obj = ResourceManager.GetObject("LastWatched", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutCoverflow {
            get {
                object obj = ResourceManager.GetObject("LayoutCoverflow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutCoverflowVanilla {
            get {
                object obj = ResourceManager.GetObject("LayoutCoverflowVanilla", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutDetails {
            get {
                object obj = ResourceManager.GetObject("LayoutDetails", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutDetailsVanilla {
            get {
                object obj = ResourceManager.GetObject("LayoutDetailsVanilla", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutPoster {
            get {
                object obj = ResourceManager.GetObject("LayoutPoster", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutPosterVanilla {
            get {
                object obj = ResourceManager.GetObject("LayoutPosterVanilla", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutRoot {
            get {
                object obj = ResourceManager.GetObject("LayoutRoot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutRootVanilla {
            get {
                object obj = ResourceManager.GetObject("LayoutRootVanilla", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutStripVanilla {
            get {
                object obj = ResourceManager.GetObject("LayoutStripVanilla", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutThumb {
            get {
                object obj = ResourceManager.GetObject("LayoutThumb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutThumbStrip {
            get {
                object obj = ResourceManager.GetObject("LayoutThumbStrip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutThumbVanilla {
            get {
                object obj = ResourceManager.GetObject("LayoutThumbVanilla", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftMenuBorderBlack {
            get {
                object obj = ResourceManager.GetObject("LeftMenuBorderBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftMenuBorderDefault {
            get {
                object obj = ResourceManager.GetObject("LeftMenuBorderDefault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lines {
            get {
                object obj = ResourceManager.GetObject("Lines", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] LinkItem {
            get {
                object obj = ResourceManager.GetObject("LinkItem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ListButton {
            get {
                object obj = ResourceManager.GetObject("ListButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ListView {
            get {
                object obj = ResourceManager.GetObject("ListView", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_bluray {
            get {
                object obj = ResourceManager.GetObject("media_bluray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_dvd {
            get {
                object obj = ResourceManager.GetObject("media_dvd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_hddvd {
            get {
                object obj = ResourceManager.GetObject("media_hddvd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] MediaInfoPanel {
            get {
                object obj = ResourceManager.GetObject("MediaInfoPanel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionActor {
            get {
                object obj = ResourceManager.GetObject("MenuOptionActor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionBackdrop {
            get {
                object obj = ResourceManager.GetObject("MenuOptionBackdrop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionBanners {
            get {
                object obj = ResourceManager.GetObject("MenuOptionBanners", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionBGFocused {
            get {
                object obj = ResourceManager.GetObject("MenuOptionBGFocused", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionBGNotFocused {
            get {
                object obj = ResourceManager.GetObject("MenuOptionBGNotFocused", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionBGNotFocusedBlack {
            get {
                object obj = ResourceManager.GetObject("MenuOptionBGNotFocusedBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionBGRed {
            get {
                object obj = ResourceManager.GetObject("MenuOptionBGRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionBGSelected {
            get {
                object obj = ResourceManager.GetObject("MenuOptionBGSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionClose {
            get {
                object obj = ResourceManager.GetObject("MenuOptionClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionConfiguration {
            get {
                object obj = ResourceManager.GetObject("MenuOptionConfiguration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionDate {
            get {
                object obj = ResourceManager.GetObject("MenuOptionDate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionDirector {
            get {
                object obj = ResourceManager.GetObject("MenuOptionDirector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionEnlarge {
            get {
                object obj = ResourceManager.GetObject("MenuOptionEnlarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionGenre {
            get {
                object obj = ResourceManager.GetObject("MenuOptionGenre", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionIndex {
            get {
                object obj = ResourceManager.GetObject("MenuOptionIndex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionLabels {
            get {
                object obj = ResourceManager.GetObject("MenuOptionLabels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionName {
            get {
                object obj = ResourceManager.GetObject("MenuOptionName", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionNone {
            get {
                object obj = ResourceManager.GetObject("MenuOptionNone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionPlayAll {
            get {
                object obj = ResourceManager.GetObject("MenuOptionPlayAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionPlayRandom {
            get {
                object obj = ResourceManager.GetObject("MenuOptionPlayRandom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionRating {
            get {
                object obj = ResourceManager.GetObject("MenuOptionRating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionRuntime {
            get {
                object obj = ResourceManager.GetObject("MenuOptionRuntime", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionShrink {
            get {
                object obj = ResourceManager.GetObject("MenuOptionShrink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionSort {
            get {
                object obj = ResourceManager.GetObject("MenuOptionSort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionStudio {
            get {
                object obj = ResourceManager.GetObject("MenuOptionStudio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionUnwatched {
            get {
                object obj = ResourceManager.GetObject("MenuOptionUnwatched", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionVertScroll {
            get {
                object obj = ResourceManager.GetObject("MenuOptionVertScroll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionViews {
            get {
                object obj = ResourceManager.GetObject("MenuOptionViews", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuOptionYear {
            get {
                object obj = ResourceManager.GetObject("MenuOptionYear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MissingPerson {
            get {
                object obj = ResourceManager.GetObject("MissingPerson", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] MovieDetailsPage {
            get {
                object obj = ResourceManager.GetObject("MovieDetailsPage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MovieInfo {
            get {
                object obj = ResourceManager.GetObject("MovieInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MPAARating {
            get {
                object obj = ResourceManager.GetObject("MPAARating", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NowPlayingViewport {
            get {
                object obj = ResourceManager.GetObject("NowPlayingViewport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Page {
            get {
                object obj = ResourceManager.GetObject("Page", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PageDefault {
            get {
                object obj = ResourceManager.GetObject("PageDefault", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PageDetailArea {
            get {
                object obj = ResourceManager.GetObject("PageDetailArea", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PageDetailAreaVanilla {
            get {
                object obj = ResourceManager.GetObject("PageDetailAreaVanilla", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PageVanilla {
            get {
                object obj = ResourceManager.GetObject("PageVanilla", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PersonButton {
            get {
                object obj = ResourceManager.GetObject("PersonButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Pivot {
            get {
                object obj = ResourceManager.GetObject("Pivot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PivotArrowLeft {
            get {
                object obj = ResourceManager.GetObject("PivotArrowLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PivotArrowLeftNoFocus {
            get {
                object obj = ResourceManager.GetObject("PivotArrowLeftNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PivotArrowRight {
            get {
                object obj = ResourceManager.GetObject("PivotArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PivotArrowRightNoFocus {
            get {
                object obj = ResourceManager.GetObject("PivotArrowRightNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] PivotItem {
            get {
                object obj = ResourceManager.GetObject("PivotItem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PopupPlay {
            get {
                object obj = ResourceManager.GetObject("PopupPlay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap poster_frame {
            get {
                object obj = ResourceManager.GetObject("poster_frame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] PosterItemTitle {
            get {
                object obj = ResourceManager.GetObject("PosterItemTitle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PosterScroller {
            get {
                object obj = ResourceManager.GetObject("PosterScroller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PosterViewItem {
            get {
                object obj = ResourceManager.GetObject("PosterViewItem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RadioFocus {
            get {
                object obj = ResourceManager.GetObject("RadioFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] RadioGroup {
            get {
                object obj = ResourceManager.GetObject("RadioGroup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RadioNoFocus {
            get {
                object obj = ResourceManager.GetObject("RadioNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RadioSelectFocus {
            get {
                object obj = ResourceManager.GetObject("RadioSelectFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RadioSelectNoFocus {
            get {
                object obj = ResourceManager.GetObject("RadioSelectNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rated_G {
            get {
                object obj = ResourceManager.GetObject("Rated_G", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rated_G_full {
            get {
                object obj = ResourceManager.GetObject("Rated_G_full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rated_NC_17 {
            get {
                object obj = ResourceManager.GetObject("Rated_NC_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rated_NC_17_full {
            get {
                object obj = ResourceManager.GetObject("Rated_NC_17_full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rated_NR {
            get {
                object obj = ResourceManager.GetObject("Rated_NR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rated_NR_full {
            get {
                object obj = ResourceManager.GetObject("Rated_NR_full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rated_PG {
            get {
                object obj = ResourceManager.GetObject("Rated_PG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rated_PG_13 {
            get {
                object obj = ResourceManager.GetObject("Rated_PG_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rated_PG_13_full {
            get {
                object obj = ResourceManager.GetObject("Rated_PG_13_full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rated_PG_full {
            get {
                object obj = ResourceManager.GetObject("Rated_PG_full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rated_R {
            get {
                object obj = ResourceManager.GetObject("Rated_R", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rated_R_full {
            get {
                object obj = ResourceManager.GetObject("Rated_R_full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rated_Unrated {
            get {
                object obj = ResourceManager.GetObject("Rated_Unrated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightMenuBorderBlack {
            get {
                object obj = ResourceManager.GetObject("RightMenuBorderBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightMenuBorderDefault {
            get {
                object obj = ResourceManager.GetObject("RightMenuBorderDefault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] RootScroller {
            get {
                object obj = ResourceManager.GetObject("RootScroller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rootscrollhilite {
            get {
                object obj = ResourceManager.GetObject("rootscrollhilite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rootscrollhilitefocus {
            get {
                object obj = ResourceManager.GetObject("rootscrollhilitefocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap roottopw {
            get {
                object obj = ResourceManager.GetObject("roottopw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ScrollableText {
            get {
                object obj = ResourceManager.GetObject("ScrollableText", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SimpleButton {
            get {
                object obj = ResourceManager.GetObject("SimpleButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SimpleSpinner {
            get {
                object obj = ResourceManager.GetObject("SimpleSpinner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sort {
            get {
                object obj = ResourceManager.GetObject("Sort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Sounds {
            get {
                object obj = ResourceManager.GetObject("Sounds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SpinnerText {
            get {
                object obj = ResourceManager.GetObject("SpinnerText", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Star_Empty {
            get {
                object obj = ResourceManager.GetObject("Star_Empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Star_Full {
            get {
                object obj = ResourceManager.GetObject("Star_Full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Star_Half {
            get {
                object obj = ResourceManager.GetObject("Star_Half", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] StarRating {
            get {
                object obj = ResourceManager.GetObject("StarRating", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] StylesBlack {
            get {
                object obj = ResourceManager.GetObject("StylesBlack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] StylesBlackExtender {
            get {
                object obj = ResourceManager.GetObject("StylesBlackExtender", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] StylesDefault {
            get {
                object obj = ResourceManager.GetObject("StylesDefault", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] StylesDefaultExtender {
            get {
                object obj = ResourceManager.GetObject("StylesDefaultExtender", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Summary {
            get {
                object obj = ResourceManager.GetObject("Summary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Tab {
            get {
                object obj = ResourceManager.GetObject("Tab", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tab_Base {
            get {
                object obj = ResourceManager.GetObject("Tab_Base", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tab_Selected {
            get {
                object obj = ResourceManager.GetObject("Tab_Selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tab_SelectedF {
            get {
                object obj = ResourceManager.GetObject("Tab_SelectedF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] TabItem {
            get {
                object obj = ResourceManager.GetObject("TabItem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TextEdit {
            get {
                object obj = ResourceManager.GetObject("TextEdit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tick {
            get {
                object obj = ResourceManager.GetObject("Tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TickPoster {
            get {
                object obj = ResourceManager.GetObject("TickPoster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TickPosterBase {
            get {
                object obj = ResourceManager.GetObject("TickPosterBase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] TitleSet {
            get {
                object obj = ResourceManager.GetObject("TitleSet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TV_14 {
            get {
                object obj = ResourceManager.GetObject("TV_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TV_G {
            get {
                object obj = ResourceManager.GetObject("TV_G", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TV_MA {
            get {
                object obj = ResourceManager.GetObject("TV_MA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TV_PG {
            get {
                object obj = ResourceManager.GetObject("TV_PG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TV_Y {
            get {
                object obj = ResourceManager.GetObject("TV_Y", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TV_Y7 {
            get {
                object obj = ResourceManager.GetObject("TV_Y7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TV_Y7_FV {
            get {
                object obj = ResourceManager.GetObject("TV_Y7_FV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Underline {
            get {
                object obj = ResourceManager.GetObject("Underline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Unwatched {
            get {
                object obj = ResourceManager.GetObject("Unwatched", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UnwatchedBase {
            get {
                object obj = ResourceManager.GetObject("UnwatchedBase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] VanillaCoverflowScroller {
            get {
                object obj = ResourceManager.GetObject("VanillaCoverflowScroller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VanillaImages {
            get {
                object obj = ResourceManager.GetObject("VanillaImages", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VanillaListScroller {
            get {
                object obj = ResourceManager.GetObject("VanillaListScroller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VanillaMenuButton {
            get {
                object obj = ResourceManager.GetObject("VanillaMenuButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VanillaMPAA {
            get {
                object obj = ResourceManager.GetObject("VanillaMPAA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VanillaPopupPlay {
            get {
                object obj = ResourceManager.GetObject("VanillaPopupPlay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VanillaPopupRadioMenu {
            get {
                object obj = ResourceManager.GetObject("VanillaPopupRadioMenu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VanillaPopupViewMenu {
            get {
                object obj = ResourceManager.GetObject("VanillaPopupViewMenu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VanillaPosterScroller {
            get {
                object obj = ResourceManager.GetObject("VanillaPosterScroller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VanillaRadioButton {
            get {
                object obj = ResourceManager.GetObject("VanillaRadioButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VanillaSimpleButton {
            get {
                object obj = ResourceManager.GetObject("VanillaSimpleButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VanillaStudio {
            get {
                object obj = ResourceManager.GetObject("VanillaStudio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewCoverflow {
            get {
                object obj = ResourceManager.GetObject("ViewCoverflow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewDetail {
            get {
                object obj = ResourceManager.GetObject("ViewDetail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ViewMenu {
            get {
                object obj = ResourceManager.GetObject("ViewMenu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewMovieDefault {
            get {
                object obj = ResourceManager.GetObject("ViewMovieDefault", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewMovieMinimal {
            get {
                object obj = ResourceManager.GetObject("ViewMovieMinimal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewMovieVanilla {
            get {
                object obj = ResourceManager.GetObject("ViewMovieVanilla", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ViewOptionsVanilla {
            get {
                object obj = ResourceManager.GetObject("ViewOptionsVanilla", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewPoster {
            get {
                object obj = ResourceManager.GetObject("ViewPoster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewThumb {
            get {
                object obj = ResourceManager.GetObject("ViewThumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewThumbstrip {
            get {
                object obj = ResourceManager.GetObject("ViewThumbstrip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Weather {
            get {
                object obj = ResourceManager.GetObject("Weather", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Writers {
            get {
                object obj = ResourceManager.GetObject("Writers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZoomPane {
            get {
                object obj = ResourceManager.GetObject("ZoomPane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
